npx aws-api-gateway-cli-test \
--username='admin@example.com' \
--password='Passw0rd!' \
--user-pool-id='us-east-1_ZPIAhMX1c' \
--app-client-id='6823aee93dp223790cf5d9btn9' \
--cognito-region='us-east-1' \
--identity-pool-id='us-east-1:1e65d5fe-0f46-4059-a24b-93307e781daf' \
--invoke-url='https://notes-api.dsplay.tv/prod' \
--api-gateway-region='us-east-1' \
--path-template='/notes' \
--method='POST' \
--body='{"content":"hello world","attachment":"hello.jpg"}'